site_name: DAM OPT — Python AI
site_description: Documentación en Markdown para Python para AI
site_url: http://localhost:8000/
theme:
  name: material
  language: es
  features:
#    - navigation.tabs
    - navigation.top 
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
#    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro

# Configura tu repositorio para mostrar "Editar esta página":
# repo_url: https://github.com/tu-usuario/tu-repo
# edit_uri: edit/main/docs/

nav:
  - Inicio: index.md
  - RA1 :
    - Entorno de trabajo: RA1/guia_python_vscode_windows.md
    - Sintaxis básica y tipos de datos: RA1/datosOperadores.md
    - Estructuras de control: RA1/estructurasControl.md 
    - Ejecución .py: RA1/practica1.md
    - Colecciones de datos: RA1/coleccionesDatos.md
    - Programas interactivos: RA1/practica2.md
    - Gestión de archivos: RA1/gestionarchivos.md
    - Clases y funciones: RA1/clasesyfunciones.md
    - Programa con POO: RA1/practica3.md
    - Resumen: RA1/resumen.md
    - Practica final: RA1/PracticaFinal.md
    - Debriefing: RA1/debriefing/index.md
  - RA2 :
    - Análisis de datos: RA2/IntroduccionAnalisisDatos.md
    - Conceptos básicos Análisis: RA2/ConceptosBasicosAnalisisDatos.md
    - Referencias: RA2/ReferenciasAnalisisDatos.  md
    - Datasets:
      - Requerimientos: RA2/AnalisisDatos/RequerimientosAnalisis.md
      - Pildoras:
          -asytpe: RA2/AnalisisDatos/pildoras/pildora_astype.md
          -numpy: RA2/AnalisisDatos/pildoras/pildora_numpy.md
          -categorical: RA2/AnalisisDatos/pildoras/pildora_categorical.md
          -coerce: RA2/AnalisisDatos/pildoras/pildora_coerce.md
          -dummies: RA2/AnalisisDatos/pildoras/pildora_dummies.md
          -estadisticos: RA2/AnalisisDatos/pildoras/pildora_estadisticas.md
          -groupby: RA2/AnalisisDatos/pildoras/pildora_groupby.md
          -histograma: RA2/AnalisisDatos/pildoras/pildora_histograma.md
          -merge: RA2/AnalisisDatos/pildoras/pildora_merge.md
          -pivot_table: RA2/AnalisisDatos/pildoras/pildora_pivot_table.md
          -relleno_nulos: RA2/AnalisisDatos/pildoras/pildora_relleno_valores.md
          -resample: RA2/AnalisisDatos/pildoras/pildora_resample.md
          -datetime: RA2/AnalisisDatos/pildoras/pildora_to_datetime.md
      - Coffe: RA2/AnalisisDatos/Coffee+Shop+Sales.md
      - Electricity: RA2/AnalisisDatos/Electricity+Consumption.md
      - LEGO-Sets: RA2/AnalisisDatos/LEGO+Sets.md
      - Pizza+Place+Sales: RA2/AnalisisDatos/Pizza+Place+Sales.md
      - Rotten-Tomatoes: RA2/AnalisisDatos/Rotten+Tomatoes+Movies.md
      - S&P+500+Stock+Prices+2014-2017: RA2/AnalisisDatos/S&P+500+Stock+Prices+2014-2017.md
      - Video+Game+Sales: RA2/AnalisisDatos/Video+Game+Sales.md
      - UFO: RA2/AnalisisDatos/ufo_sightings_scrubbed.md
      - winemag-data-130k-v2: RA2/AnalisisDatos/winemag-data-130k-v2.md
      - Spotify: RA2/AnalisisDatos/Spotify.md
      - World+Cup: RA2/AnalisisDatos/World+Cup.md

plugins:
 - mermaid2:
      version: 10.0.2
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
 - search:
      lang: es

